package com.yusy.keykeeper.ui.theme

import androidx.compose.ui.graphics.Color


val myLightPrimary = Color(0xFF006973)
val myLightOnPrimary = Color(0xFFFFFFFF)
val myLightPrimaryContainer = Color(0xFF93F1FF)
val myLightOnPrimaryContainer = Color(0xFF001F23)
val myLightSecondary = Color(0xFF4A6266)
val myLightOnSecondary = Color(0xFFFFFFFF)
val myLightSecondaryContainer = Color(0xFFCDE7EC)
val myLightOnSecondaryContainer = Color(0xFF051F22)
val myLightTertiary = Color(0xFF525E7D)
val myLightOnTertiary = Color(0xFFFFFFFF)
val myLightTertiaryContainer = Color(0xFFD9E2FF)
val myLightOnTertiaryContainer = Color(0xFF0D1B37)
val myLightError = Color(0xFFBA1A1A)
val myLightErrorContainer = Color(0xFFFFDAD6)
val myLightOnError = Color(0xFFFFFFFF)
val myLightOnErrorContainer = Color(0xFF410002)
val myLightBackground = Color(0xFFFAFDFD)
val myLightOnBackground = Color(0xFF191C1D)
val myLightSurface = Color(0xFFFAFDFD)
val myLightOnSurface = Color(0xFF191C1D)
val myLightSurfaceVariant = Color(0xFFDBE4E6)
val myLightOnSurfaceVariant = Color(0xFF3F484A)
val myLightOutline = Color(0xFF6F797A)
val myLightInverseOnSurface = Color(0xFFEFF1F1)
val myLightInverseSurface = Color(0xFF2E3132)
val myLightInversePrimary = Color(0xFF00DBEF)
//val myLightShadow = Color(0xFF000000)
val myLightSurfaceTint = Color(0xFF006973)
val myLightOutlineVariant = Color(0xFFBFC8CA)
val myLightScrim = Color(0xFF000000)

val myDarkPrimary = Color(0xFF00DBEF)
val myDarkOnPrimary = Color(0xFF00363C)
val myDarkPrimaryContainer = Color(0xFF004F57)
val myDarkOnPrimaryContainer = Color(0xFF93F1FF)
val myDarkSecondary = Color(0xFFB1CBCF)
val myDarkOnSecondary = Color(0xFF1C3438)
val myDarkSecondaryContainer = Color(0xFF334B4E)
val myDarkOnSecondaryContainer = Color(0xFFCDE7EC)
val myDarkTertiary = Color(0xFFBAC6EA)
val myDarkOnTertiary = Color(0xFF23304D)
val myDarkTertiaryContainer = Color(0xFF3A4664)
val myDarkOnTertiaryContainer = Color(0xFFD9E2FF)
val myDarkError = Color(0xFFFFB4AB)
val myDarkErrorContainer = Color(0xFF93000A)
val myDarkOnError = Color(0xFF690005)
val myDarkOnErrorContainer = Color(0xFFFFDAD6)
val myDarkBackground = Color(0xFF191C1D)
val myDarkOnBackground = Color(0xFFE1E3E3)
val myDarkSurface = Color(0xFF191C1D)
val myDarkOnSurface = Color(0xFFE1E3E3)
val myDarkSurfaceVariant = Color(0xFF3F484A)
val myDarkOnSurfaceVariant = Color(0xFFBFC8CA)
val myDarkOutline = Color(0xFF899294)
val myDarkInverseOnSurface = Color(0xFF191C1D)
val myDarkInverseSurface = Color(0xFFE1E3E3)
val myDarkInversePrimary = Color(0xFF006973)
//val myDarkShadow = Color(0xFF000000)
val myDarkSurfaceTint = Color(0xFF00DBEF)
val myDarkOutlineVariant = Color(0xFF3F484A)
val myDarkScrim = Color(0xFF000000)

//val seed = Color(0xFF00DEF3)
